language: node_js
node_js:
  - 5
script: cd app && npm test && cd .. && npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
